// Generated by gencpp from file sanitation_control/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SANITATION_CONTROL_MESSAGE_ADDTWOINTS_H
#define SANITATION_CONTROL_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <sanitation_control/AddTwoIntsRequest.h>
#include <sanitation_control/AddTwoIntsResponse.h>


namespace sanitation_control
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace sanitation_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sanitation_control::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::sanitation_control::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::sanitation_control::AddTwoInts > {
  static const char* value()
  {
    return "sanitation_control/AddTwoInts";
  }

  static const char* value(const ::sanitation_control::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::sanitation_control::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::sanitation_control::AddTwoInts > 
template<>
struct MD5Sum< ::sanitation_control::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sanitation_control::AddTwoInts >::value();
  }
  static const char* value(const ::sanitation_control::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sanitation_control::AddTwoIntsRequest> should match 
// service_traits::DataType< ::sanitation_control::AddTwoInts > 
template<>
struct DataType< ::sanitation_control::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::sanitation_control::AddTwoInts >::value();
  }
  static const char* value(const ::sanitation_control::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sanitation_control::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::sanitation_control::AddTwoInts > 
template<>
struct MD5Sum< ::sanitation_control::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sanitation_control::AddTwoInts >::value();
  }
  static const char* value(const ::sanitation_control::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sanitation_control::AddTwoIntsResponse> should match 
// service_traits::DataType< ::sanitation_control::AddTwoInts > 
template<>
struct DataType< ::sanitation_control::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::sanitation_control::AddTwoInts >::value();
  }
  static const char* value(const ::sanitation_control::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SANITATION_CONTROL_MESSAGE_ADDTWOINTS_H
