// Generated by gencpp from file sanitation_control/trigger_textResponse.msg
// DO NOT EDIT!


#ifndef SANITATION_CONTROL_MESSAGE_TRIGGER_TEXTRESPONSE_H
#define SANITATION_CONTROL_MESSAGE_TRIGGER_TEXTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sanitation_control
{
template <class ContainerAllocator>
struct trigger_textResponse_
{
  typedef trigger_textResponse_<ContainerAllocator> Type;

  trigger_textResponse_()
    : succeeded(false)
    , message()  {
    }
  trigger_textResponse_(const ContainerAllocator& _alloc)
    : succeeded(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _succeeded_type;
  _succeeded_type succeeded;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::sanitation_control::trigger_textResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sanitation_control::trigger_textResponse_<ContainerAllocator> const> ConstPtr;

}; // struct trigger_textResponse_

typedef ::sanitation_control::trigger_textResponse_<std::allocator<void> > trigger_textResponse;

typedef boost::shared_ptr< ::sanitation_control::trigger_textResponse > trigger_textResponsePtr;
typedef boost::shared_ptr< ::sanitation_control::trigger_textResponse const> trigger_textResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sanitation_control::trigger_textResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sanitation_control::trigger_textResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sanitation_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sanitation_control::trigger_textResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sanitation_control::trigger_textResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sanitation_control::trigger_textResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sanitation_control::trigger_textResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sanitation_control::trigger_textResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sanitation_control::trigger_textResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sanitation_control::trigger_textResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92f07022ad10c1e4ff936618bca1e212";
  }

  static const char* value(const ::sanitation_control::trigger_textResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92f07022ad10c1e4ULL;
  static const uint64_t static_value2 = 0xff936618bca1e212ULL;
};

template<class ContainerAllocator>
struct DataType< ::sanitation_control::trigger_textResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sanitation_control/trigger_textResponse";
  }

  static const char* value(const ::sanitation_control::trigger_textResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sanitation_control::trigger_textResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool succeeded\n\
string message\n\
\n\
";
  }

  static const char* value(const ::sanitation_control::trigger_textResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sanitation_control::trigger_textResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeeded);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct trigger_textResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sanitation_control::trigger_textResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sanitation_control::trigger_textResponse_<ContainerAllocator>& v)
  {
    s << indent << "succeeded: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeeded);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SANITATION_CONTROL_MESSAGE_TRIGGER_TEXTRESPONSE_H
