// Generated by gencpp from file sanitation_control/trigger_text.msg
// DO NOT EDIT!


#ifndef SANITATION_CONTROL_MESSAGE_TRIGGER_TEXT_H
#define SANITATION_CONTROL_MESSAGE_TRIGGER_TEXT_H

#include <ros/service_traits.h>


#include <sanitation_control/trigger_textRequest.h>
#include <sanitation_control/trigger_textResponse.h>


namespace sanitation_control
{

struct trigger_text
{

typedef trigger_textRequest Request;
typedef trigger_textResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct trigger_text
} // namespace sanitation_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sanitation_control::trigger_text > {
  static const char* value()
  {
    return "92f07022ad10c1e4ff936618bca1e212";
  }

  static const char* value(const ::sanitation_control::trigger_text&) { return value(); }
};

template<>
struct DataType< ::sanitation_control::trigger_text > {
  static const char* value()
  {
    return "sanitation_control/trigger_text";
  }

  static const char* value(const ::sanitation_control::trigger_text&) { return value(); }
};


// service_traits::MD5Sum< ::sanitation_control::trigger_textRequest> should match 
// service_traits::MD5Sum< ::sanitation_control::trigger_text > 
template<>
struct MD5Sum< ::sanitation_control::trigger_textRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sanitation_control::trigger_text >::value();
  }
  static const char* value(const ::sanitation_control::trigger_textRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sanitation_control::trigger_textRequest> should match 
// service_traits::DataType< ::sanitation_control::trigger_text > 
template<>
struct DataType< ::sanitation_control::trigger_textRequest>
{
  static const char* value()
  {
    return DataType< ::sanitation_control::trigger_text >::value();
  }
  static const char* value(const ::sanitation_control::trigger_textRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sanitation_control::trigger_textResponse> should match 
// service_traits::MD5Sum< ::sanitation_control::trigger_text > 
template<>
struct MD5Sum< ::sanitation_control::trigger_textResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sanitation_control::trigger_text >::value();
  }
  static const char* value(const ::sanitation_control::trigger_textResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sanitation_control::trigger_textResponse> should match 
// service_traits::DataType< ::sanitation_control::trigger_text > 
template<>
struct DataType< ::sanitation_control::trigger_textResponse>
{
  static const char* value()
  {
    return DataType< ::sanitation_control::trigger_text >::value();
  }
  static const char* value(const ::sanitation_control::trigger_textResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SANITATION_CONTROL_MESSAGE_TRIGGER_TEXT_H
