(cl:defpackage sanitation_control-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "TRIGGER_TEXT"
   "<TRIGGER_TEXT-REQUEST>"
   "TRIGGER_TEXT-REQUEST"
   "<TRIGGER_TEXT-RESPONSE>"
   "TRIGGER_TEXT-RESPONSE"
  ))

